/**
 * Created by: artDev
 * Copyright (c) 2025 artDev, SerpentSpirale, CADIndie.
 * For use under LGPL-3.0
 */

// Added manually as needed
GLESFUNC(glDrawElementsIndirect,PFNGLDRAWELEMENTSINDIRECTPROC)
GLESFUNC(glMultiDrawArraysEXT,PFNGLMULTIDRAWARRAYSEXTPROC)
GLESFUNC(glMultiDrawElementsEXT,PFNGLMULTIDRAWELEMENTSEXTPROC)
GLESFUNC(glGetTexLevelParameteriv,PFNGLGETTEXLEVELPARAMETERIVPROC)
GLESFUNC(glGetTexLevelParameterfv,PFNGLGETTEXLEVELPARAMETERFVPROC)
GLESFUNC(glDrawElementsBaseVertex, PFNGLDRAWELEMENTSBASEVERTEXPROC)
GLESFUNC(glDrawElementsBaseVertexOES, PFNGLDRAWELEMENTSBASEVERTEXOESPROC)
GLESFUNC(glDrawElementsBaseVertexEXT, PFNGLDRAWELEMENTSBASEVERTEXEXTPROC)
GLESFUNC(glBlendEquationi, PFNGLBLENDEQUATIONIPROC)
GLESFUNC(glBlendEquationiOES, PFNGLBLENDEQUATIONIOESPROC)
GLESFUNC(glBlendEquationiEXT, PFNGLBLENDEQUATIONIEXTPROC)
GLESFUNC(glBlendEquationSeparatei, PFNGLBLENDEQUATIONSEPARATEIPROC)
GLESFUNC(glBlendEquationSeparateiOES, PFNGLBLENDEQUATIONSEPARATEIOESPROC)
GLESFUNC(glBlendEquationSeparateiEXT, PFNGLBLENDEQUATIONSEPARATEIEXTPROC)
GLESFUNC(glBlendFunci, PFNGLBLENDFUNCIPROC)
GLESFUNC(glBlendFunciOES, PFNGLBLENDFUNCIOESPROC)
GLESFUNC(glBlendFunciEXT, PFNGLBLENDFUNCIEXTPROC)
GLESFUNC(glBlendFuncSeparatei, PFNGLBLENDFUNCSEPARATEIPROC)
GLESFUNC(glBlendFuncSeparateiOES, PFNGLBLENDFUNCSEPARATEIOESPROC)
GLESFUNC(glBlendFuncSeparateiEXT, PFNGLBLENDFUNCSEPARATEIEXTPROC)
GLESFUNC(glColorMaski, PFNGLCOLORMASKIPROC)
GLESFUNC(glColorMaskiOES, PFNGLCOLORMASKIOESPROC)
GLESFUNC(glColorMaskiEXT, PFNGLCOLORMASKIEXTPROC)
GLESFUNC(glBufferStorageEXT, PFNGLBUFFERSTORAGEEXTPROC)
GLESFUNC(glTexBuffer, PFNGLTEXBUFFERPROC);
GLESFUNC(glTexBufferRange, PFNGLTEXBUFFERRANGEPROC);
GLESFUNC(glTexBufferEXT, PFNGLTEXBUFFEREXTPROC)
GLESFUNC(glTexBufferRangeEXT, PFNGLTEXBUFFERRANGEEXTPROC)
GLESFUNC(glMultiDrawElementsIndirectEXT, PFNGLMULTIDRAWELEMENTSINDIRECTEXTPROC)
GLESFUNC(glGetQueryObjecti64vEXT, PFNGLGETQUERYOBJECTI64VEXTPROC)
GLESFUNC(glGetQueryObjectui64vEXT, PFNGLGETQUERYOBJECTUI64VEXTPROC)
GLESFUNC(glQueryCounterEXT, PFNGLQUERYCOUNTEREXTPROC)

/* GLES 3.1+ - Compute Shader e relacionados */
/* Use EXT variants for functions not available in core GLES 3.1 on Android */
GLESFUNC(glMultiDrawArraysIndirectEXT, PFNGLMULTIDRAWARRAYSINDIRECTEXTPROC)
/* glCopyBufferSubData and glMultiDrawElementsIndirectEXT are already in es3_functions.h */
